workflows:
  my-workflow:
    name: Release version
    environment:
      vars:
        CACHED_JSON: Encrypted(Z0FBQUFBQmVzSk9IRnZXQWlGOURoY3Exano4WmZTbkgwZDJMcXk1aEN2SFAtSlBGaW52QzlWNnVtSE9PRHNUalg4blZ4R2FtcEJfSExFb3RIYUg1bkNWVDdsMmE5bFYyeXZoUTlGMmVadnZrZDRCdWtvX0cwSHZEUzZ2Q0pvQVpKUWd4TUQ3RHR6UjBEak4zWmFzZWtIOWN5X0swS3MyakZEdDFmcF8taGdBTHlDNUxtLU9VQmJZQnlURnpaOUJwLTNELVpUWTFxN1RIYVhjeGhmVVZiTmd1T1BMcHREaEF0NkJRZXpjdERNMnNrbTJfb0FOSUVpU29pNV9PX29ZaW54NDNEcFBIbnU0dFNKeEcxeW9JT25UbVJWLXhhWXRfbHFRdnlJVHp5ZXFaOGhjMXdhaHFmX2dCZ1c4aUEtenI2U3ZVU2xEUG51Ny1VeHU3ZTJFODdaTG1yTF9hdTM1Q0NUYUxiY0dhXzhpd3Rsb0lscklKdTlhNlVXbUFRd0dNb29hMTRBMmVmcnRreWtyN185SDRCNVA5RVZSbnByZ2wzak9EMVVqdk1fb0xvaC1GbGM5RlliYWMxajBrS0xBOWk3by1zWHYwdFlqaTg2X3RDVlpNeVBwaS0wcFU3bFZKRXgtWUhMZmdwbjd0WTYtQzdoMkk5TWt1TzJyV0hMU21ENnEtZEppM09pVExvUXh1Tl9TVG9zUngwbTFZVm9oWjJrVDZIaFpiVTdkRGdVLUdxRVRLb24tN0QweGhlZU1FTERyRXJVTzR5WngxOXBhWTdKZm5EMXpTaHFTeTBJV01FZXVWbmI1VFNSRFJyRUw0cVdhTF9rLUFQZGJSanNMVTRHZTJra0dnNmtKcmJhMjZCdURUTDAzOVNaeHBuSy00WkJMVldqSkREclV1ZWd1TWpGeDU4bWdJdkx3Y0NNUjhkeEZNcXA2YV96Vks=)
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'test_codemagic'
          include: true
          source: true
    scripts:
      - flutter packages pub get
      - ./scripts/cache.sh
      - flutter pub publish --dry-run
      - flutter pub publish -f
