workflows:
  my-workflow:
    name: Release version
    environment:
      vars:
        CACHED_JSON: Encrypted(Z0FBQUFBQmRyY1FLWXIwVEhqdWphdjRhQ0xubkdoOGJ2bThkNmh4YmdXbFB3S2wyNTN2OERoV3c0YWU0OVBERG42d3Rfc2N0blNDX3FfblZxbUc4d2pWUHJBSVppbXNXNC04U1VqcGlnajZ2VnJVMVFWc3lZZ289)
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'test_codemagic'
          include: true
          source: true
    scripts:
      - flutter packages pub get
      - ./scripts/cache.sh
      - flutter pub publish --dry-run
      - flutter pub publish -f
